### ISSUE TITLE
Add requirements.txt or setup.py

### ISSUE THREAD

**Issue by dzlab** [LynnHo/CycleGAN-Tensorflow-Simple#29]
When I try to run the training it fails with the following error (missing dependencies)
```
$ CUDA_VISIBLE_DEVICES=0 python train.py --dataset summer2winter_yosemite
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    py.args_to_yaml(py.join(output_dir, 'settings.yml'), args)
  File "/content/CycleGAN-Tensorflow-2/pylib/argument.py", line 81, in args_to_yaml
    serialization.save_yaml(path, vars(namespace), **kwagrs)
  File "/content/CycleGAN-Tensorflow-2/pylib/serialization.py", line 36, in save_yaml
    import oyaml as yaml
ModuleNotFoundError: No module named 'oyaml'
```
Can you add a `requirements.txt` or a `setup.py` so that the setup can be easy

**Comment by LynnHo** [comment]
@dzlab Thanks for the suggestion, I will add it in the spare time.
