### ISSUE TITLE
Errors while changing batch size

### ISSUE THREAD

**Issue by vishal16babu** [LynnHo/CycleGAN-Tensorflow-Simple#3]
I am getting errors when I'm trying to change batch size from 1 to 2 for the apple2orange dataset. The error log is : 
```
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "train.py", line 177, in <module>
    im.imwrite(im.immerge(sample_opt, 2, 3), '%s/Epoch_(%d)_(%dof%d).jpg' % (save_dir, epoch, it_epoch, batch_epoch))
  File "/home/vishal/vishal/btp/CYCLE_GAN/CycleGAN-Tensorflow-PyTorch-Simple-master/image_utils.py", line 132, in immerge
    img[j * h:j * h + h, i * w:i * w + w, ...] = image
ValueError: could not broadcast input array from shape (256,256,3) into shape (0,256,3)
```

**Comment by LynnHo** [comment]
![image](https://user-images.githubusercontent.com/16457298/35027967-8085eaaa-fb8e-11e7-90e5-6805326016f3.png)
@vishal16babu try to replace the 'batch_size' here with '1', the test batch size should be one in this code.
