### ISSUE TITLE
Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.

### ISSUE THREAD

**Issue by Curiosit** [LynnHo/CycleGAN-Tensorflow-Simple#33]
I am getting this error while trying to run train.py
any ideas?

**Comment by LynnHo** [comment]
@Curiosit Did you put the data into the correct place? Or did you totally follow the REAME.md steps?

**Comment by philthestone** [comment]
@LynnHo 
I do run into the same problem
I've put the images in the right structure which means i do have a dataset folder with 4 subfolders trainA, trainB, testA, testB. 
All folders contain 1024x1024 png images. 

Now if i run follwing command in google colab
CUDA_VISIBLE_DEVICES=0
!python /content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/train.py \
  --dataset /content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/vgs4to1 \
  --load_size 1024 \
  --crop_size 1024 \
  --pool_size=1
  
i get follwing ouptut: 

2021-07-15 14:35:25.612941: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
/usr/local/lib/python3.7/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.5.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
2021-07-15 14:35:26.936486: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-15 14:35:26.950406: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.951010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-07-15 14:35:26.951065: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 14:35:26.953754: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-07-15 14:35:26.953834: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2021-07-15 14:35:26.955490: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2021-07-15 14:35:26.955849: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-07-15 14:35:26.957738: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.10
2021-07-15 14:35:26.958501: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-07-15 14:35:26.958700: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-07-15 14:35:26.958807: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.959412: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.959948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-15 14:35:26.982496: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.983061: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2021-07-15 14:35:26.983141: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.983801: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:26.984389: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2021-07-15 14:35:26.984462: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-07-15 14:35:27.586875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-07-15 14:35:27.586927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2021-07-15 14:35:27.586941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2021-07-15 14:35:27.587100: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:27.587761: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:27.588415: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-07-15 14:35:27.589053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15433 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
Traceback (most recent call last):
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/train.py", line 51, in <module>
    A_B_dataset, len_dataset = data.make_zip_dataset(A_img_paths, B_img_paths, args.batch_size, args.load_size, args.crop_size, training=True, repeat=False)
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/data.py", line 44, in make_zip_dataset
    A_dataset = make_dataset(A_img_paths, batch_size, load_size, crop_size, training, drop_remainder=True, shuffle=shuffle, repeat=A_repeat)
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/data.py", line 29, in make_dataset
    repeat=repeat)
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/tf2lib/data/dataset.py", line 127, in disk_image_batch_dataset
    repeat=repeat)
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/tf2lib/data/dataset.py", line 77, in memory_data_batch_dataset
    repeat=repeat)
  File "/content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/tf2lib/data/dataset.py", line 32, in batch_dataset
    dataset = dataset.map(map_fn, num_parallel_calls=n_map_threads)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1932, in map
    preserve_cardinality=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4526, in __init__
    use_legacy_function=use_legacy_function)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3712, in __init__
    self._function = fn_factory()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3135, in get_concrete_function
    *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3100, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3687, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 3617, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py", line 695, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/tf2lib/data/dataset.py:113 map_fn_  *
        return map_fn(*parse_fn(*args))
    /content/drive/MyDrive/MA/CycleGan/CycleGAN-Tensorflow-2_0/CycleGAN-Tensorflow-2-master/tf2lib/data/dataset.py:107 parse_fn  *
        img = tf.io.read_file(path)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/io_ops.py:138 read_file  **
        return gen_io_ops.read_file(filename, name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_io_ops.py:561 read_file
        "ReadFile", filename=filename, name=name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py:545 _apply_op_helper
        (prefix, dtypes.as_dtype(input_arg.type).name))

    TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.
    

I've tried to run the code with the horse2zebra dataset. that does work (at least it starts training...). So the setup with google colab should not be the problem. But as soon as i change the input path to my own dataset it fails. 

When i start running the code a settings.yml file is created within the dataset folder.

Any ideas?

- png files not possible?
- not enough images in folders? (trainA --> 126, trainB -->231, testA --> 74, testB --> 61)
- naming of the files is for example D0000433_0.png. Each image has a different name.
- images do have 4 channels (RGBA)

Thanks for the help!

Edit:

The problem was the png fileformat. Had do change it in train.py line 45 to 58:

A_img_paths = py.glob(py.join(args.datasets_dir, args.dataset, 'trainA'), '*.**png**')
B_img_paths = py.glob(py.join(args.datasets_dir, args.dataset, 'trainB'), '*.**png**')
A_B_dataset, len_dataset = data.make_zip_dataset(A_img_paths, B_img_paths, args.batch_size, args.load_size, args.crop_size, training=True, repeat=False)

A2B_pool = data.ItemPool(args.pool_size)
B2A_pool = data.ItemPool(args.pool_size)

A_img_paths_test = py.glob(py.join(args.datasets_dir, args.dataset, 'testA'), '*.**png**')
B_img_paths_test = py.glob(py.join(args.datasets_dir, args.dataset, 'testB'), '*.**png**')
A_B_dataset_test, _ = data.make_zip_dataset(A_img_paths_test, B_img_paths_test, args.batch_size, args.load_size, args.crop_size, training=False, repeat=True)
